### ISSUE TITLE
about BOSCH-traffic-light-dataset

### ISSUE THREAD

**Issue by BrownSweater** [berktepebag/Traffic-light-detection-with-YOLOv3-BOSCH-traffic-light-dataset#1]
thanks for you code, but i can't download from Official website.
can u provide BOSCH-traffic-light-dataset for  google drive or baidudisk.
If u can provide your trained weights  at the same time, it is better.

**Comment by berktepebag** [comment]
Hi, thanks for your interest. I will have to check if there will be or not a legal issue if I upload it to somewhere. If it is not possible I will try to make a smaller version of it (since it is 6 GB it will take a bit time to upload with 4mbit anyway). You can find weights under backup, I have trained only for half an hour with gtx 1070 so the results are not super.

**Comment by BrownSweater** [comment]
> Hi, thanks for your interest. I will have to check if there will be or not a legal issue if I upload it to somewhere. If it is not possible I will try to make a smaller version of it (since it is 6 GB it will take a bit time to upload with 4mbit anyway). You can find weights under backup, I have trained only for half an hour with gtx 1070 so the results are not super.

thanks , i only need rgb dataset.

**Comment by berktepebag** [comment]
Licence seems ok with sharing but I'm asking them now to avoid any problems.

**Comment by BrownSweater** [comment]
> Licence seems ok with sharing but I'm asking them now to avoid any problems.

OK

**Comment by berktepebag** [comment]
Can you send me an e-mail to berk.tepebag@gmail.com so I can share the dataset.

**Comment by FlyingAnt2018** [comment]
> Can you send me an e-mail to [berk.tepebag@gmail.com](mailto:berk.tepebag@gmail.com) so I can share the dataset.

hello,may have your BOSCH small traffic light dataset? Best wishes to you!

**Comment by berktepebag** [comment]
You can download it via these links. But I have been informed that dataset can also be found at Kaggle. 

https://drive.google.com/file/d/1F7ImiuW2DoTAnq2PzRe_z4aPNSeqHqAV/view?usp=sharing, https://drive.google.com/file/d/1RnT5ILdibzZTSN0bsD1m09Gm8n74YLrp/view?usp=sharing, https://drive.google.com/file/d/1Zy-PKM4z94SroClcV_-0V2wJPKlShxI7/view?usp=sharing, https://drive.google.com/file/d/1w2HkUmFp-XPkpJpT23LWYpE3f6tIXtKI/view?usp=sharing

**Comment by FlyingAnt2018** [comment]
Thanks for your reply.
Best wishes.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Berk ***@***.***> |
| Date | 11/09/2022 21:39 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [berktepebag/Traffic-light-detection-with-YOLOv3-BOSCH-traffic-light-dataset] about BOSCH-traffic-light-dataset (#1) |

You can download it via these links. But I have been informed that dataset can also be found at Kaggle.

https://drive.google.com/file/d/1F7ImiuW2DoTAnq2PzRe_z4aPNSeqHqAV/view?usp=sharing, https://drive.google.com/file/d/1RnT5ILdibzZTSN0bsD1m09Gm8n74YLrp/view?usp=sharing, https://drive.google.com/file/d/1Zy-PKM4z94SroClcV_-0V2wJPKlShxI7/view?usp=sharing, https://drive.google.com/file/d/1w2HkUmFp-XPkpJpT23LWYpE3f6tIXtKI/view?usp=sharing
