### ISSUE TITLE
video demo

### ISSUE THREAD

**Issue by tomorrow-rain** [berktepebag/Traffic-light-detection-with-YOLOv3-BOSCH-traffic-light-dataset#5]
Can you provide the video demo during the test? 
Thanks.

**Comment by berktepebag** [comment]
Do you mean the result or the input video? Best

**Comment by tomorrow-rain** [comment]
The input video. Since I used “yolov3-tiny-bosch_40000.weights”  file to test my own video but didn't detect any targets, I wanted to do a test using your input video.

**Comment by tomorrow-rain** [comment]
> Do you mean the result or the input video? Best

The input video. Since I used “yolov3-tiny-bosch_40000.weights” file to test my own video but didn't detect any targets, I wanted to do a test using your input video.

**Comment by berktepebag** [comment]
You can use this one, which was recorded by me and very low quality https://drive.google.com/file/d/1--6ODp18lSp0hix7ihCbWLhMB_4yJb0y/view?usp=sharing or this one from Youtube with much better quality https://www.youtube.com/watch?v=2LXwr2bRNic  . If it doesn't work again let me know.

**Comment by tomorrow-rain** [comment]
> You can use this one, which was recorded by me and very low quality https://drive.google.com/file/d/1--6ODp18lSp0hix7ihCbWLhMB_4yJb0y/view?usp=sharing or this one from Youtube with much better quality https://www.youtube.com/watch?v=2LXwr2bRNic . If it doesn't work again let me know.

Ok, I can detect the traffic lights now after downloading the video you provided. Thank you very much for your reply!
